nav:
  Home: https://kpl0111.github.io
  Blog: /
  Timeline: /archives/
  Github: https://github.com/kpl0111
  About: https://kpl0111.github.io/about

projects_url: https://github.com/kpl0111

customize:
    gravatar:
        email: kunpengl0111@gmail.com
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon.ico
        gravator: false
      apple:
        url: /images/favicon.ico
        gravator: false
    social_links:
        github: https://github.com/kpl0111
        twitter: https://twitter.com/Nefelib31847846
    post_count: 5
    highlight: lightcode

# keept it like this to add the root path (probably a bug)
root: ..

solar:
    # factor between 0 (fast), 1(normal), 2(very slow)  
    speed: 1
    sun_image: /images/sun.png
    earth_image: /images/earth.png
    jupiter_image: /images/jupiter.png
    mars_image: /images/mars.png
    mercury_image: /images/mercury.png
    shadow_image: /images/shadow.png
    venus_image: /images/venus.png

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
